language: java
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew --stacktrace --info build sonarqube

before_deploy:
  - ./gradlew publishPlugin

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/distributions/java2smali-*.zip
  skip_cleanup: true
  on:
    repo: ollide/intellij-java2smali
    tags: true
